#!/usr/bin/env python3
"""
ingestion/emit_to_datahub.py

Pushes Kobo's mock rights/royalty dataset (generated by
data/generate_mock_data.py) into a running DataHub instance as real Dataset
entities, wired together with lineage and enriched with structured
properties.

PREREQUISITE: structured property definitions must already be registered:
    datahub properties upsert -f ingestion/structured_properties.yaml
(this script will warn, but not fail loudly, if that step was skipped --
DataHub will simply reject the property values it doesn't recognize)

Entity/lineage model (see DOCUMENTATION.md section 2 for the full rationale):

    rights_holder --(upstream of)--> ownership_split --(upstream of)--> track
                                                                            |
                                                                     (upstream of)
                                                                            v
                                                                     usage_event
                                                                            |
                                                                     (upstream of)
                                                                            v
                                                                       payout

All entities are modeled as DataHub Datasets on a synthetic "kobo" platform,
since Kobo isn't a real ingestion source -- this is a deliberate, documented
simplification (see DOCUMENTATION.md section 2.3) that keeps the whole
pipeline usable through DataHub's standard MCP tool surface without needing
custom entity types.

Usage:
    python3 ingestion/emit_to_datahub.py
    python3 ingestion/emit_to_datahub.py --seed-dir data/seed --platform kobo
"""

import argparse
import csv
import logging
import os
import sys
from collections import defaultdict
from typing import Dict, List, Optional

from dotenv import load_dotenv

import datahub.emitter.mce_builder as builder
from datahub.emitter.mcp import MetadataChangeProposalWrapper
from datahub.emitter.rest_emitter import DatahubRestEmitter
from datahub.metadata.com.linkedin.pegasus2avro.dataset import (
    DatasetLineageTypeClass,
    UpstreamClass,
    UpstreamLineage,
)
from datahub.metadata.schema_classes import (
    DatasetPropertiesClass,
    GlobalTagsClass,
    StatusClass,
    TagAssociationClass,
)
from datahub.specific.dataset import DatasetPatchBuilder

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
log = logging.getLogger("kobo.ingestion")

DOMAIN_TAG = "urn:li:tag:kobo-royalty-domain"


# ---------------------------------------------------------------------------
# CSV loading
# ---------------------------------------------------------------------------

def load_csv(path: str) -> List[Dict[str, str]]:
    if not os.path.exists(path):
        raise SystemExit(
            f"Missing input file: {path}\n"
            f"Did you run 'make mock-data' (or "
            f"'python3 data/generate_mock_data.py') first?"
        )
    with open(path, newline="") as f:
        return list(csv.DictReader(f))


# ---------------------------------------------------------------------------
# URN helpers
# ---------------------------------------------------------------------------

def track_urn(platform: str, env: str, track_id: str) -> str:
    return builder.make_dataset_urn(platform, f"tracks.{track_id}", env)


def holder_urn(platform: str, env: str, holder_id: str) -> str:
    return builder.make_dataset_urn(platform, f"rights_holders.{holder_id}", env)


def split_urn(platform: str, env: str, split_id: str) -> str:
    return builder.make_dataset_urn(platform, f"ownership_splits.{split_id}", env)


def event_urn(platform: str, env: str, event_id: str) -> str:
    return builder.make_dataset_urn(platform, f"usage_events.{event_id}", env)


def payout_urn(platform: str, env: str, payout_id: str) -> str:
    return builder.make_dataset_urn(platform, f"payouts.{payout_id}", env)


# ---------------------------------------------------------------------------
# Emission helpers
# ---------------------------------------------------------------------------

class Emitter:
    """Thin wrapper around DatahubRestEmitter that logs and continues on
    failure rather than crashing the whole ingestion run -- one bad row
    shouldn't take down the other 700 rows during a demo prep session."""

    def __init__(self, gms_url: str, token: Optional[str]):
        self.rest_emitter = DatahubRestEmitter(gms_server=gms_url, token=token)
        self.rest_emitter.test_connection()
        self.errors = 0

    def emit_properties(self, urn: str, name: str, description: str, custom_properties: dict):
        try:
            mcp = MetadataChangeProposalWrapper(
                entityUrn=urn,
                aspect=DatasetPropertiesClass(
                    name=name,
                    description=description,
                    customProperties={k: str(v) for k, v in custom_properties.items()},
                ),
            )
            self.rest_emitter.emit(mcp)

            # Without an explicit Status aspect, some DataHub versions treat
            # freshly-created entities as soft-deleted until something else
            # touches them.
            status_mcp = MetadataChangeProposalWrapper(
                entityUrn=urn,
                aspect=StatusClass(removed=False),
            )
            self.rest_emitter.emit(status_mcp)

            tag_mcp = MetadataChangeProposalWrapper(
                entityUrn=urn,
                aspect=GlobalTagsClass(tags=[TagAssociationClass(tag=DOMAIN_TAG)]),
            )
            self.rest_emitter.emit(tag_mcp)
        except Exception as e:
            self.errors += 1
            log.error(f"Failed to emit properties for {urn}: {e}")

    def emit_structured_properties(self, urn: str, properties: dict):
        try:
            builder_patch = DatasetPatchBuilder(urn)
            for prop_id, value in properties.items():
                if value is None or value == "":
                    continue
                builder_patch = builder_patch.set_structured_property(prop_id, value)
            for patch_mcp in builder_patch.build():
                self.rest_emitter.emit(patch_mcp)
        except Exception as e:
            self.errors += 1
            log.error(f"Failed to emit structured properties for {urn}: {e}")

    def emit_lineage(self, urn: str, upstream_urns: List[str]):
        if not upstream_urns:
            return
        try:
            upstream_lineage = UpstreamLineage(
                upstreams=[
                    UpstreamClass(dataset=u, type=DatasetLineageTypeClass.TRANSFORMED)
                    for u in upstream_urns
                ]
            )
            mcp = MetadataChangeProposalWrapper(entityUrn=urn, aspect=upstream_lineage)
            self.rest_emitter.emit(mcp)
        except Exception as e:
            self.errors += 1
            log.error(f"Failed to emit lineage for {urn}: {e}")


# ---------------------------------------------------------------------------
# Main ingestion routine
# ---------------------------------------------------------------------------

def run(seed_dir: str, platform: str, env: str, gms_url: str, token: Optional[str]):
    log.info(f"Loading mock data from {seed_dir} ...")
    tracks = load_csv(os.path.join(seed_dir, "tracks.csv"))
    holders = load_csv(os.path.join(seed_dir, "rights_holders.csv"))
    splits = load_csv(os.path.join(seed_dir, "ownership_splits.csv"))
    events = load_csv(os.path.join(seed_dir, "usage_events.csv"))
    payouts = load_csv(os.path.join(seed_dir, "payouts.csv"))

    log.info(
        f"Loaded {len(tracks)} tracks, {len(holders)} rights holders, "
        f"{len(splits)} splits, {len(events)} usage events, {len(payouts)} payouts."
    )

    log.info(f"Connecting to DataHub at {gms_url} ...")
    emitter = Emitter(gms_url, token)
    log.info("Connection OK.")

    # --- Rights holders ---
    log.info("Emitting rights_holders ...")
    for h in holders:
        urn = holder_urn(platform, env, h["holder_id"])
        emitter.emit_properties(
            urn=urn,
            name=h["name"],
            description=f"{h['holder_type'].title()} rights holder.",
            custom_properties={"holder_type": h["holder_type"], "payee_id": h["payee_id"]},
        )
        emitter.emit_structured_properties(
            urn,
            {
                "io.kobo.rightsHolder.holderType": h["holder_type"],
                "io.kobo.rightsHolder.payeeId": h["payee_id"],
            },
        )

    # --- Ownership splits (also computes per-track total split %) ---
    log.info("Emitting ownership_splits ...")
    track_total_split: Dict[str, float] = defaultdict(float)
    track_split_urns: Dict[str, List[str]] = defaultdict(list)

    for s in splits:
        urn = split_urn(platform, env, s["split_id"])
        rh_urn = holder_urn(platform, env, s["holder_id"])
        track_id = s["track_id"]
        pct = float(s["split_pct"])

        track_total_split[track_id] += pct
        track_split_urns[track_id].append(urn)

        emitter.emit_properties(
            urn=urn,
            name=s["split_id"],
            description=(
                f"{s['split_pct']}% ownership split, territory={s['territory']}, "
                f"right_type={s['right_type']}"
            ),
            custom_properties={
                "track_id": track_id,
                "holder_id": s["holder_id"],
                "split_pct": s["split_pct"],
                "territory": s["territory"],
                "right_type": s["right_type"],
            },
        )
        emitter.emit_structured_properties(
            urn,
            {
                "io.kobo.split.splitPct": pct,
                "io.kobo.split.territory": s["territory"],
                "io.kobo.split.rightType": s["right_type"],
                "io.kobo.split.licenseStart": s["license_start"],
                "io.kobo.split.licenseEnd": s["license_end"],
            },
        )
        # rights_holder --(upstream of)--> ownership_split
        emitter.emit_lineage(urn, [rh_urn])

    # --- Tracks ---
    log.info("Emitting tracks ...")
    for t in tracks:
        urn = track_urn(platform, env, t["track_id"])
        total_split = round(track_total_split.get(t["track_id"], 0.0), 2)

        emitter.emit_properties(
            urn=urn,
            name=t["title"],
            description=f"Track by {t['primary_artist']} (ISRC {t['isrc']}).",
            custom_properties={
                "isrc": t["isrc"],
                "primary_artist": t["primary_artist"],
                "total_split_pct": total_split,
            },
        )
        emitter.emit_structured_properties(
            urn,
            {
                "io.kobo.track.isrc": t["isrc"],
                "io.kobo.track.primaryArtist": t["primary_artist"],
                "io.kobo.track.totalSplitPct": total_split,
            },
        )
        # ownership_split(s) --(upstream of)--> track
        emitter.emit_lineage(urn, track_split_urns.get(t["track_id"], []))

    # --- Usage events ---
    log.info("Emitting usage_events ...")
    for e in events:
        urn = event_urn(platform, env, e["event_id"])
        trk_urn = track_urn(platform, env, e["track_id"])

        emitter.emit_properties(
            urn=urn,
            name=e["event_id"],
            description=(
                f"{e['event_type']} on {e['platform']} in {e['territory']} "
                f"at {e['timestamp']}"
            ),
            custom_properties={
                "track_id": e["track_id"],
                "event_type": e["event_type"],
                "territory": e["territory"],
                "platform": e["platform"],
                "timestamp": e["timestamp"],
                "unit_count": e["unit_count"],
                "event_value": e["event_value"],
            },
        )
        emitter.emit_structured_properties(
            urn,
            {
                "io.kobo.event.eventType": e["event_type"],
                "io.kobo.event.territory": e["territory"],
                "io.kobo.event.platform": e["platform"],
                "io.kobo.event.timestamp": e["timestamp"],
                "io.kobo.event.unitCount": float(e["unit_count"]),
                "io.kobo.event.eventValue": float(e["event_value"]),
            },
        )
        # track --(upstream of)--> usage_event
        emitter.emit_lineage(urn, [trk_urn])

    # --- Payouts ---
    log.info("Emitting payouts ...")
    for p in payouts:
        urn = payout_urn(platform, env, p["payout_id"])
        evt_urn = event_urn(platform, env, p["usage_event_id"])

        emitter.emit_properties(
            urn=urn,
            name=p["payout_id"],
            description=(
                f"{p['amount_paid']} {p['currency']} paid to {p['payee_id']} "
                f"for statement period {p['statement_period']}"
            ),
            custom_properties={
                "usage_event_id": p["usage_event_id"],
                "payee_id": p["payee_id"],
                "amount_paid": p["amount_paid"],
                "currency": p["currency"],
                "statement_period": p["statement_period"],
            },
        )
        emitter.emit_structured_properties(
            urn,
            {
                "io.kobo.payout.amountPaid": float(p["amount_paid"]),
                "io.kobo.payout.currency": p["currency"],
                "io.kobo.payout.payeeId": p["payee_id"],
                "io.kobo.payout.statementPeriod": p["statement_period"],
            },
        )
        # usage_event --(upstream of)--> payout
        emitter.emit_lineage(urn, [evt_urn])

    log.info("Done.")
    if emitter.errors:
        log.warning(
            f"{emitter.errors} emission(s) failed. Check that structured "
            f"properties were registered first: "
            f"'datahub properties upsert -f ingestion/structured_properties.yaml'"
        )
        sys.exit(1)
    else:
        log.info(
            f"All entities emitted successfully. Open the DataHub UI and "
            f"search for the 'kobo-royalty-domain' tag to browse them."
        )


def main():
    load_dotenv()

    parser = argparse.ArgumentParser(description="Emit Kobo mock data into DataHub")
    parser.add_argument("--seed-dir", default="data/seed")
    parser.add_argument("--platform", default="kobo")
    parser.add_argument("--env", default="PROD")
    parser.add_argument("--gms-url", default=os.environ.get("DATAHUB_GMS_URL", "http://localhost:8080"))
    parser.add_argument("--token", default=os.environ.get("DATAHUB_GMS_TOKEN"))
    args = parser.parse_args()

    run(
        seed_dir=args.seed_dir,
        platform=args.platform,
        env=args.env,
        gms_url=args.gms_url,
        token=args.token,
    )


if __name__ == "__main__":
    main()